"""history

Revision ID: ac01bcf2a99d
Revises: 5bcf971f46aa
Create Date: 2022-03-05 02:20:58.249400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac01bcf2a99d'
down_revision = '5bcf971f46aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repair', sa.Column('registration_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repair', 'registration_time')
    # ### end Alembic commands ###
